title: Hack Special Education
production_url: http://blog.learningwings.co/
permalink: pretty

# meta
markdown: kramdown

# assets
sass:
  style: :compressed
  sass_dir: _sass

# homepage stuff
author: Lori Herrick
author_image: http://placekitten.com/g/500/500
tagline: A certified intervention specialist, and an artist at heart, with 16 years experience helping kids with disabilities. I have a Bachelor's degree in fine arts and a Master's degree in education. More importantly, a passion for finding creative ways to meet the unique needs of struggling students.  
