title: Hack Special Education
production_url: http://hackspecialeducation.com/
permalink: /:title/

# meta
markdown: kramdown

# assets
sass:
  style: :compressed
  sass_dir: _sass

# homepage stuff
author: Lori Herrick
author_image: /images/profile.jpg
tagline: A certified intervention specialist, and an artist at heart, with 16 years experience helping kids with disabilities. I have a Bachelor's degree in fine arts and a Master's degree in education. But more importantly, I have a passion for finding creative ways to meet the unique needs of struggling students.
